### ISSUE TITLE
Flash of stretched images

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#1]
Every time I reload the page I see for a few milliseconds the images stretched.
This is happening on the homepage but also on the detail pages.
I'm on Edge 90
![image](https://user-images.githubusercontent.com/6048794/119723157-7050fa80-be6d-11eb-84d8-edf61c368c8f.png)

**Comment by maeligg** [comment]
Fixed in https://github.com/maeligg/my-online-cookbook/commit/c5f57f7618c54191d072b33e243eb5495941df54
