### ISSUE TITLE
Is the whole website translatable?

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#10]
For example "servings" & "ingredients" are not translated in French on your website.
(Also you wrote onion :D )
![image](https://user-images.githubusercontent.com/6048794/119729644-3126a780-be75-11eb-9b9d-e0aa207bbae3.png)

**Comment by maeligg** [comment]
Fixed in https://github.com/maeligg/my-online-cookbook/commit/6921c5d93dc3a4bca2f8035c046206ff1b5615f2
