### ISSUE TITLE
No H2 on recipes page

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#11]
For example here there is \<h1>, then all \<h3> but never \h2.
https://mael-recettes.netlify.app/recipes/

Same on a recipe, we go from \h1 to \h3
https://mael-recettes.netlify.app/recipes/chirashi-saumon-avocat/

**Comment by maeligg** [comment]
Not ideal, but tbh I don't care that much. I'd rather keep the h3 to facilitate reuse of the cards on the homepage where there is an h2.
