### ISSUE TITLE
iOs (maybe Safari) | Search is not working

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#13]
On my phone I can open the form, type in something but I've got no result.
Tested on iOs 14.4.2

**Comment by robindevouge** [comment]
Not working either on MacOS Firefox (Chrome & Safari ok)

**Comment by maeligg** [comment]
It's working for me on iOS (emulated) and on MacOS Firefox. 😭
Still trying to reproduce this bug... @robindevouge do you see anything in the console ? What version of MaxOS + Firefox are you on ?

**Comment by robindevouge** [comment]
Well I checked Netlify settings and since I forced HTTPS the issue is not occuring anymore, search is fine now :)
