### ISSUE TITLE
All searches require lower case

### ISSUE THREAD

**Issue by ZekeZDev** [maeligg/my-online-cookbook#17]
all search items are changed into lowercase in the search.njk file yet the user search is not meaning the user will not get any results for eg. "Simple brownies". Instead they would search "simple brownies" to get a result. I am not experienced with alpine.js and my "fix" was quite messy I hope that a proper fix can be found because this is a major issue for a template such as this.

**Comment by maeligg** [comment]
Good catch, thanks for reporting this bug ! Fixed in https://github.com/maeligg/my-online-cookbook/commit/46f909218985bc5eb3f0fd2fd3d51a6aae024b52
