### ISSUE TITLE
Flash of unstyled fonts

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#2]
Everytime I refresh the page I see the wrong fonts for a few frames before new ones are loading.
But with the cache I should not have that issue as the fonts don't need to be loaded.
This is happening on local & online.
Edge 90
![image](https://user-images.githubusercontent.com/6048794/119723307-99718b00-be6d-11eb-8ed7-4bda8c366bdd.png)

**Comment by maeligg** [comment]
Fixed in https://github.com/maeligg/my-online-cookbook/commit/bf88dfa74d79fa9c85dcaa21ff683990c00a1c7e
