### ISSUE TITLE
Difference between local & demo

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#3]
See on the localhost I have a "u-free-text" class on the body but not on the live demo where it's "about".
Maybe the demo is just not up to date as your website is working well?
Because of that there are a few differences between both environnement.
![image](https://user-images.githubusercontent.com/6048794/119723725-10a71f00-be6e-11eb-856b-ac1009ee902a.png)

**Comment by maeligg** [comment]
Fixed, latest version wasn't deployed.
