### ISSUE TITLE
Recipe title font is big on mobile

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#4]
See if I have a longer recipe name how it's quickly overflowing:
![image](https://user-images.githubusercontent.com/6048794/119724552-223cf680-be6f-11eb-8b8b-358c12244389.png)

**Comment by maeligg** [comment]
Fixed in https://github.com/maeligg/my-online-cookbook/commit/eae9e806b31f761d9bb717931a0177a7301e9f9c
