### ISSUE TITLE
iOs bugs

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#6]
I know you will hate me for this but...

- [ ] iOs doesn't support gap with flex at the moment, making the nav & the list of tags broken
- [x] The search icon is cropped
- [ ] There are more issues because of the gap (like on the recipe page, I don't have space between ingredients & instructions)

![IMG_4904](https://user-images.githubusercontent.com/6048794/119725894-c8d5c700-be70-11eb-8148-067ddf3424a7.PNG)

**Comment by maeligg** [comment]
Let's try only supporting the latest iOS version for now and see how this goes.
