### ISSUE TITLE
Recipe card - a11y

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#7]
It's not super good to have that many elements in a link tag.
Only the title should be the link and the link can expand the whole card with a pseudo element for example.
Also, I don't think a h3 for the name makes sense as there is no section/article/aside parent.
![image](https://user-images.githubusercontent.com/6048794/119726135-12261680-be71-11eb-80c9-ede453c58f04.png)

**Comment by maeligg** [comment]
Fixed in https://github.com/maeligg/my-online-cookbook/commit/c8082fc32cd3313586cebfdf92bc187db9e12530
