### ISSUE TITLE
Semantic Tags page

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#8]
I wouldn't use a section for only the title and a section for the list of recipes;
They should be grouped to make the title "Favourite" the title of the recipes list.
![image](https://user-images.githubusercontent.com/6048794/119726542-82349c80-be71-11eb-8c59-bdbab8476d0b.png)

**Comment by maeligg** [comment]
Not ideal but I don't think it's a huge a11y issue and it makes my life easier as I can use the sections for styling.
