### ISSUE TITLE
Use target blank

### ISSUE THREAD

**Issue by Mamboleoo** [maeligg/my-online-cookbook#9]
I personnaly prefer using target blank for external links ;)
![image](https://user-images.githubusercontent.com/6048794/119728902-4818ca00-be74-11eb-889e-189e73ff9e8b.png)

Same for the Source of a recipe:
![image](https://user-images.githubusercontent.com/6048794/119730842-7dbeb280-be76-11eb-8973-db3b444d6c96.png)

**Comment by maeligg** [comment]
Fixed in https://github.com/maeligg/my-online-cookbook/commit/e2c932b1e444db40d22c99f17b0bc8df69ab6087
